### ISSUE TITLE
Eudyptula challenge has closed

### ISSUE THREAD

**Issue by daxtens** [ajdlinux/KernelPRBot#3]
So per http://eudyptula-challenge.org/, they're not accepting new people. We should point people to something else.

**Comment by ajdlinux** [comment]
Will remove - though I'm not sure of anything to add in its place.

(It kinda irritates me that the Eudyptula Challenge was one of the very few good resources for new kernel devs and was mentioned or linked to from approximately everywhere, yet it's run by a pseudonym and is super opaque, unlike the kernel development process...)
